pipeline {
    agent any

    environment {
        IMAGE_NAME = 'boardgame'
        WORKER_INVENTORY = 'boardgame-infra/ansible/inventory.ini'

        // ✅ use your real docker hub username here
        DOCKERHUB_USER = 'sumitshirke369'

        SONARQUBE_ENV = 'SonarQube'
    }

    tools {
        maven 'Maven'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/sumitshirke333/Boardgame-project-.git',
                    credentialsId: 'github-credentials'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'mvn clean test'
            }
            post {
                unsuccessful {
                    error("❌ Tests failed! Stopping the pipeline.")
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
                    sh 'mvn verify sonar:sonar'
                }
            }
        }

        stage('Build Maven Project') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t $DOCKERHUB_USER/$IMAGE_NAME:latest .
                docker images
                '''
            }
        }

        stage('Trivy Scan') {
            steps {
                sh '''
                trivy image --exit-code 0 --severity HIGH,CRITICAL $DOCKERHUB_USER/$IMAGE_NAME:latest
                '''
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $DOCKER_USER/$IMAGE_NAME:latest
                    '''
                }
            }
        }

        stage('Deploy to Worker Node') {
            steps {
                sh '''
                ansible-playbook -i $WORKER_INVENTORY boardgame-infra/ansible/deploy-app.yml
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline completed successfully! 🚀'
        }
        failure {
            echo '❌ Pipeline failed. Check logs above for details.'
        }
    }
}
